<!-- resources/views/livewire/user/land-lord/tenant/tenants-list-pdf.blade.php -->
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>All Tenants</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
            color: #333;
        }
        .container {
            width: 100%;
            max-width: 800px;
            margin: 0 auto;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            padding-bottom: 10px;
            border-bottom: 1px solid #ddd;
        }
        h1 {
            font-size: 24px;
            color: #333;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 30px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #777;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Tenants List</h1>
            <p>Generated on: {{ date('F d, Y') }}</p>
            <p>Total Tenants: {{ count($tenants) }}</p>
        </div>

        <table>
            <thead>
                <tr>
                    <th>#</th>
                    <th>Tenant ID</th>
                    <th>Tenant Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Company</th>
                </tr>
            </thead>
            <tbody>
                @foreach($tenants as $index => $tenant)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $tenant->tenant_id }}</td>
                    <td>{{ $tenant->tenant_name }}</td>
                    <td>{{ $tenant->phone }}</td>
                    <td>{{ $tenant->email }}</td>
                    <td>{{ $tenant->company_name }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="footer">
            <p>This document is for official use only.</p>
            <p>Generated by Property Management System</p>
        </div>
    </div>
</body>
</html>
